# Yaml file for training the networks

# name of the output directory within output
name: best

# settings for the flow model, if load is True, the model will be loaded from the given location
# otherwise a new one is created
flow:
  n_dim: 6
  n_blocks: 8
  n_nodes: 256
  cond_dims: 6
  load: False
  model_location: 21cm_cINN/params/flow.pth

# If load is True, the model will be loaded from the given location
# otherwise a new one is created
cnn:
  load: False
  model_location: 21cm_cINN/params/cnn.pth

# training settings
train:
  # path to the data
  data_path : /remote/gpu01a/heneka/21cmlightcones/pure_simulations
  # tain_network is either cnn, flow or both
  train_network: cnn
  # if train_network is flow, the path to the output of the cnn model is needed
  # or it will be run once
  cnn_output_path: output/
  epochs: 30 
  batch_size: 8
  lr: 0.0004
  # more scheduler options are available, look at the code
  scheduler: 'StepLR'
  scheduler_params:
    step_size: 500
    gamma: 0.5
